### ISSUE TITLE
what if we want to use vuex?

### ISSUE THREAD

**Issue by mehrancodes** [cklmercer/vue-laravel-forms#2]
every time that I submit a form,  a promise will be created. that's good but what if we use vue-laravel-forms with vuex?
I don't know whether there will be any issue.

**Comment by cklmercer** [comment]
I haven't tried it with vuex. Honestly, I wrote `vue-stash` and never
really learned `vuex`. I've tried it and understand the gist of it, but I
don't know much past the basics.

That said, I'm open to pull requests. Also, I'm willing to take it on
myself, but it'll be a little a little while before it surfaces to the top
of my list.

**Comment by cklmercer** [comment]
closing stale issues before transfer.
