### ISSUE TITLE
How to send json?

### ISSUE THREAD

**Issue by hotrush** [cklmercer/vue-laravel-forms#3]
not multipart/form-data

**Comment by cklmercer** [comment]
I'm sorry, but this isn't configurable at the moment.

**Comment by hotrush** [comment]
it's a pity, i want to send an array of ids, but comma-separated values looks weird. thanks

**Comment by cklmercer** [comment]
The `Illuminate\Http\Request` class should be able to turn that into an
array for you. That or you can use `explode()` and `collect()`. Sorry for
the inconvenience.

**Comment by hotrush** [comment]
using `explode`, seems it does not convert automatically
