### ISSUE TITLE
Support older browsers ?

### ISSUE THREAD

**Issue by pelletiermaxime** [cklmercer/vue-laravel-forms#4]
Hi,

Your plugin is using Promise, but you don't include any polyfill, so this plugin gave errors in IE. You might want to either add this to the readme or add a polyfill like babel-polyfill.

Thanks!

**Comment by cklmercer** [comment]
Thanks for the feedback! I'll add a note to the readme for now. This plugin
will be getting some big updates before the end of the year. I'll add this
to my list of issues to address.

**Comment by cklmercer** [comment]
closing stale issues before transfer.
