### ISSUE TITLE
Assigning initial values

### ISSUE THREAD

**Issue by Kuuseorg** [cklmercer/vue-laravel-forms#5]
How should one assign default values from $parent dataset? I have something like this:
`
forms: {
 accountForm: {
  firstName: this.$parent.user.firstName,
  lastName: this.$parent.user.lastName
 }
},
`

**Comment by cklmercer** [comment]
Is your method working for you? This package doesn't really imply any "best practices". If what you have is working, then I'd probably just stick with doing it that way.

**Comment by Kuuseorg** [comment]
Hi! Thanks for response. Unfortunately this does not work. I have not found single solution beside giving info as a hardcoded string...

**Comment by cklmercer** [comment]
I believe that's because of the time during the lifecycle that the forms are initialized. The easiest solution, off the top of my head, would be to hook into the lifecycle again at a later point and update the form from there.

**Comment by Kuuseorg** [comment]
Okey, yeah - makes sense :) Thanks!
